---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: resource-tutorial
    type: git
    icon: github
    source:
      uri: ((github-resource-tutorial))
      branch: ((branch-resource-tutorial))

  - name: resource-s3-file-1
    type: s3
    icon: database
    source:
      bucket: ((s3-bucket-1))
      regexp: (.*).txt
      access_key_id: ((s3-access-key))
      secret_access_key: ((s3-access-secret))
      endpoint: ((s3-endpoint))
      disable_ssl: true
      use_v4: true

  - name: resource-s3-file-2
    type: s3
    icon: database
    source:
      bucket: ((s3-bucket-2))
      regexp: (.*).txt
      access_key_id: ((s3-access-key))
      secret_access_key: ((s3-access-secret))
      endpoint: ((s3-endpoint))
      disable_ssl: true
      use_v4: true
  
  - name: image-resource
    type: docker-image
    icon: docker
    source: {repository: ((image-resource))}

  - name: notify
    type: slack-notification
    icon: message-alert
    source:
      url: ((slack-webhook))

jobs:
  - name: create-file-1-put-on-s3-bucket
    public: true
    serial: true
    plan:
      - get: image-resource
      - get: resource-tutorial
      - get: resource-s3-file-1        
      - task: create-output-file
        image: image-resource
        file: resource-tutorial/tasks/task_create_output.yml
        params:
          COMMAND: "$(uname -a)"
          FILENAME: "uname"
      - put: resource-s3-file-1
        params:
          file: /outputs/uname-*.txt
          acl: public-read

  - name: create-file-2-put-on-s3-bucket
    public: true
    serial: true
    plan:
      - get: image-resource
      - get: resource-tutorial
      - get: resource-s3-file-2        
      - task: create-output-file
        image: image-resource
        file: resource-tutorial/tasks/task_create_output.yml
        params:
          COMMAND: "$(date)"
          FILENAME: "date"
      - put: resource-s3-file-2
        params:
          file: /outputs/date-*.txt
          acl: public-read

  - name: read-file-1-from-s3-bucket
    public: true
    plan:
      - get: image-resource
      - get: resource-tutorial
      - get: resource-s3-file-1
        passed: [create-file-1-put-on-s3-bucket]
        trigger: true 
      - task: read-file-from-s3-bucket
        image: image-resource
        vars:
          RESOURCE: "resource-s3-file-1"
        params:
          FILEINPUT: "resource-s3-file-1"
        file: resource-tutorial/tasks/task_show_output_s3.yml
    on_success:
      put: notify
      params:
        text: "Congratulations! pipeline: $BUILD_PIPELINE_NAME > Job: $BUILD_JOB_NAME successed! "
    on_failure:
      put: notify
      params:
        text: "Alert! pipeline: $BUILD_PIPELINE_NAME > Job: $BUILD_JOB_NAME failed! "
    on_error:
      put: notify
      params:
        text: "Alert! pipeline: $BUILD_PIPELINE_NAME > Job: $BUILD_JOB_NAME got an error!" 
    on_abort:
      put: notify
      params:
        text: "Abort! pipeline: $BUILD_PIPELINE_NAME > Job: $BUILD_JOB_NAME aborted! " 

  - name: read-file-2-from-s3-bucket
    public: true
    plan:
      - get: image-resource
      - get: resource-tutorial
      - get: resource-s3-file-2
        passed: [create-file-2-put-on-s3-bucket]
        trigger: true 
      - task: read-file-from-s3-bucket
        image: image-resource
        params:
          RESOURCE: "resource-s3-file-2"
        file: resource-tutorial/tasks/task_show_output_s3.yml
    on_success:
      put: notify
      params:
        text: "Congratulations! pipeline: $BUILD_PIPELINE_NAME > Job: $BUILD_JOB_NAME successed! "
    on_failure:
      put: notify
      params:
        text: "Alert! pipeline: $BUILD_PIPELINE_NAME > Job: $BUILD_JOB_NAME failed! "
    on_error:
      put: notify
      params:
        text: "Alert! pipeline: $BUILD_PIPELINE_NAME > Job: $BUILD_JOB_NAME got an error!" 
    on_abort:
      put: notify
      params:
        text: "Abort! pipeline: $BUILD_PIPELINE_NAME > Job: $BUILD_JOB_NAME aborted! " 