---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: ((github-resource-tutorial))
      branch: ((branch-resource-tutorial))

  - name: resource-s3
    type: s3
    source:
      bucket: ((s3-bucket))
      regexp: time(.*).txt
      access_key_id: ((s3-access-key))
      secret_access_key: ((s3-access-secret))
      endpoint: ((s3-endpoint))
      disable_ssl: true
      use_v4: true
  
  - name: image-resource
    type: docker-image
    source: {repository: ((image-resource))}

jobs:
  - name: create-file-put-on-s3-bucket
    public: true
    serial: true
    plan:
      - get: image-resource
      - get: resource-tutorial
      - get: resource-s3        
      - task: create-output-file
        image: image-resource
        file: resource-tutorial/tasks/task_create_output.yml       
      - put: resource-s3
        params:
          file: /outputs/time.txt
          acl: public-read             
  - name: read-file-from-s3-bucket
    public: true
    plan:
      - get: image-resource
      - get: resource-tutorial
      - get: resource-s3
        passed: [create-file-put-on-s3-bucket]
        trigger: true 
      - task: read-file-from-s3-bucket
        image: image-resource
        file: resource-tutorial/tasks/task_show_output_s3.yml
