---
resources:
  - name: resource-tutorial
    type: s3
    source:
      bucket: ((s3-bucket))
      regexp: tasks/task_hello(.*).yml
      access_key_id: ((s3-access-key))
      secret_access_key: ((s3-access-secret))
      endpoint: ((s3-endpoint))
      #cloudfront_url: ((s3-endpoint))
      disable_ssl: true
      use_v4: true
  
  - name: image-resource
    type: docker-image
    source: {repository: ((image-resource))}

jobs:
  - name: s3-bucket
    public: true
    plan:
      - get: image-resource
      - get: resource-tutorial          
      - task: show-files
        config:    
          platform: linux
          image_resource:
          #  type: docker-image
            source: {image: image-resource } #{repository: busybox}
          inputs:
          - name: resource-tutorial
          run:
            args:
            - -alR
            path: ls 
    
    #  - task: hello-world
    #    image: image-resource
    #    file: resource-tutorial/task_hello_world.yml
    #    params:
    #      GREETING: "((message))"
        #trigger: true
    #  - task: create-output-file
    #    image: image-resource
    #    file: /my-bucket/tasks//task_create_output.yml
     
    #  - task: show-output-file
     #   image: image-resource
      #  file: /my-bucket/tasks/task_show_output.yml