---
resource_types:
  - name: concourse-kubectl-resource-type
    type: docker-image
    source: 
      repository: jmkarthik/concourse-kubectl-resource
      tag: latest

resources:
  - name: concourse-kubectl-resource
    icon: ship-wheel
    type: concourse-kubectl-resource-type
    source:
      api_server_uri: ((server)) # get credentials from credentials-file
      namespace: ((namespace)) # get credentials from credentials-file
      certificate_authority_data: ((cad)) # get credentials from vault
      token: ((token)) # get credentials from vault

  - name: resource-tutorial
    type: git
    icon: github
    source:
      uri: ((github-resource-tutorial)) # get credentials from credentials-file
      branch: ((branch-resource-tutorial)) # get credentials from credentials-file

jobs:
  - name: deploy-nginx
    public: true
    serial: true
    plan:
    - get: resource-tutorial
    - put: concourse-kubectl-resource
      params:
        file: resource-tutorial/k8s-files/nginx.yaml