---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: ((github-resource-tutorial))
      branch: ((branch-resource-tutorial))
  - name: image-resource
    type: docker-image
    source: {repository: ((image-resource))}

jobs:
  - name: show-some-files
    public: true
    plan:
      - get: image-resource
      - get: resource-tutorial
      #  trigger: true
      - task: create-output-file
        image: image-resource
        file: resource-tutorial/tasks/task_create_output.yml
        params:
          COMMAND: "((command-1))" # get credentials from credentials-file
          FILENAME: "((filename-1))" # get credentials from credentials-file
      - task: show-output-file
        image: image-resource
        params:
          PATHINPUT: "outputs"
          FILEINPUT: "((filename-1))"
        vars:
          RESOURCE: "outputs"
        file: resource-tutorial/tasks/task_show_output.yml