---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: ((github-resource-tutorial))
      branch: ((branch-resource-tutorial))
  - name: image-resource
    type: docker-image
    source: {repository: ((image-resource))}

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: image-resource-((image-resource))
      - get: resource-tutorial
        trigger: true
      - task: hello-world
        image: image-resource-((image-resource))
        file: resource-tutorial/tasks/task_hello_world.yml
        params:
          GREETING: "Hello Pipeline"