---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: ((github-resource-tutorial))
      branch: ((branch-resource-tutorial))

  - name: busy-box
    type: docker-image
    source: {repository: ((image-resource-tutorial))}

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: resource-tutorial
        trigger: true
      - task: hello-world
        file: resource-tutorial/tasks/task_hello_world.yml
        params:
          GREETING: "((message))"